### ISSUE TITLE
Deprecated notice in widget

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-tabs#12]
![tabs](https://user-images.githubusercontent.com/1271053/27644484-b178a39c-5bf1-11e7-887b-e740b534c980.png)

>Notice: genesis_get_additional_image_sizes is deprecated since version 2.5.0! Use wp_get_additional_image_sizes instead. in /wp-includes/functions.php on line 3831

**Comment by nickcernis** [comment]
Confirmed × 2.

<img width="520" alt="widgets_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/32232916-12891de4-be51-11e7-8f20-39902bcadf16.png">
