### ISSUE TITLE
Strict Standards Errors and unexpected output on activation

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-tabs#13]
Currently, what's in develop has strict standards errors and `The plugin generated 212 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.`

https://github.com/copyblogger/genesis-tabs/pull/4/commits/810917d2f2f9068d48fb2950377d55b0ddc59f00 resolves the strict standards part of that.

**Comment by dreamwhisper** [comment]
@nathanrice I still get this in the develop branch:

> The plugin generated 212 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by nickcernis** [comment]
I see the same with debug mode on due to a function deprecation notice.

Adapting `genesis_tabs_activation_check()` to use `wp_get_theme()` instead of `get_theme_data()` solves this for me.

```php
function genesis_tabs_activation_check() {

	$latest = '2.5.0';

	$theme = wp_get_theme( 'genesis' );

	if ( 'genesis' != basename( TEMPLATEPATH ) ) {
		deactivate_plugins( plugin_basename( __FILE__ ) ); /** Deactivate ourself */
		wp_die( sprintf( __( 'Sorry, you can\'t activate unless <a href="%s">Genesis</a> is installed and active.', 'apl' ), 'https://my.studiopress.com/themes/genesis/' ) );
	}

	if ( version_compare( $theme->get( 'Version' ), $latest, '<' ) ) {
		deactivate_plugins( plugin_basename( __FILE__ ) ); /** Deactivate ourself */
		wp_die( sprintf( __( 'Sorry, you cannot activate without <a href="%s">Genesis %s</a> or greater.', 'apl' ), 'https://my.studiopress.com/documentation/usage/genesis-features/how-to-update-the-genesis-framework/', $latest ) );
	}

}```

**Comment by dreamwhisper** [comment]
`define( 'WP_DEBUG_LOG', true );` allows you to see the error.

PHP Notice:  get_theme_data is <strong>deprecated</strong> since version 3.4.0! Use wp_get_theme() instead. in public_html/dev/wp-includes/functions.php on line 3831

That also resolves it for me.

**Comment by dreamwhisper** [comment]
@nathanrice confirmed
