### ISSUE TITLE
More tag doesn't work

### ISSUE THREAD

**Issue by r-diamond** [copyblogger/genesis-tabs#6]
I've tested this on RM and non-RM sites.
Settings: 
Show Content
Content Limit 0

Using the More Tag to split the content still results in the entire content displaying. I've tested in Focus, Eleven40, and a customized third-party theme.

The image shows the same post in a Featured Posts widget and a Featured Tab widget, with the content properly truncated in Featured Posts.

![tabs issue](https://cloud.githubusercontent.com/assets/3864662/3937675/86cc7a54-24b0-11e4-9be2-03386915c035.jpg)

**Comment by dreamwhisper** [comment]
Andrea and I tested this and can't replicate. Closing.
